//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_typepart
    {
        public System.Guid TYPEID { get; set; }
        public System.Guid PARTID { get; set; }
        public string TypeName { get; set; }
        public string PartName { get; set; }
        public string TypePartName { get; set; }
    }
}
