//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_birth
    {
        public Nullable<int> BirthDay { get; set; }
        public Nullable<int> BirthMonth { get; set; }
        public Nullable<int> age { get; set; }
        public string FIO { get; set; }
        public string Dolzhnost { get; set; }
        public string WorkPhone { get; set; }
        public string DepShortName { get; set; }
        public string EntShortName { get; set; }
    }
}
