//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_infoview
    {
        public System.Guid PHID { get; set; }
        public System.Guid DEPID { get; set; }
        public System.Guid ENTID { get; set; }
        public string EntName { get; set; }
        public string EntShortName { get; set; }
        public string EntAddress { get; set; }
        public string EntPhoneKod { get; set; }
        public int ParentGptn { get; set; }
        public string DepName { get; set; }
        public string DepShortName { get; set; }
        public string Dolzhnost { get; set; }
        public string FIO { get; set; }
        public string WorkPhoneCity { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhoneCity { get; set; }
        public string HomePhone { get; set; }
        public string EMail { get; set; }
        public string Peiger { get; set; }
        public Nullable<System.DateTime> BirthDayDate { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public string PhotoImg { get; set; }
        public string FullInfo { get; set; }
        public Nullable<int> DEPKAT { get; set; }
        public Nullable<int> ENTKAT { get; set; }
        public Nullable<int> KAT { get; set; }
    }
}
